services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  app:
    build: .
    depends_on:
      - postgres
    restart: on-failure:3
    links:
      - postgres:${POSTGRES_HOST}
    ports:
      - ${PORT}:${PORT}